plugins {
    id 'org.springframework.boot'
}

dependencies {
    implementation project(':common')
    implementation project(':seller')
    implementation project(':shopper')
    implementation project(':product')

    runtimeOnly 'com.h2database:h2'

    testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

bootJar {
    mainClass = 'com.demo.book.springtdd.SpringTddBookApplication'
}
